export {default as AllCampuses} from './AllCampuses'
export {default as NavBar} from './NavBar'
export {default as AllStudents} from './AllStudents'
export {default as SingleCampus} from './SingleCampus'
export {default as SplashPage} from './SplashPage'
export {default as SingleStudent} from './SingleStudent'